### ISSUE TITLE
Fix .yml file

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/QuoteGarden#1]
Configure Travis-ci build file for NodeJS

**Comment by AbderrahimSoubaiElidrissi** [comment]
Any other details ?

**Comment by pprathameshmore** [comment]
Add Travis-ci build file for NodeJS

**Comment by pprathameshmore** [comment]
![Annotation 2019-10-04 195732](https://user-images.githubusercontent.com/17108186/66215467-3acc2c00-e6e1-11e9-8ac0-8770b269c35a.jpg)
Currently not configured any builds for this project.

**Comment by sudhir512kj** [comment]
@pprathameshmore I would like to work on it.

**Comment by pprathameshmore** [comment]
Go ahead @sudhir512kj

**Comment by sudhir512kj** [comment]
assign it to me

**Comment by pprathameshmore** [comment]
The issue is open for others

**Comment by AbderrahimSoubaiElidrissi** [comment]
@pprathameshmore Check this #2
