### ISSUE TITLE
Add new features using genre field

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/QuoteGarden#11]
Now we have collections of more than 75k documents. Most have a genre, so we can implement a feature of fetching documents based on genre.

**Comment by Shankhanil** [comment]
Let me try working on this one!

**Comment by pprathameshmore** [comment]
Yeah, go ahead!

**Comment by Shankhanil** [comment]
I have submitted a solution, but the build is taking like 7min+. does TravisCI usually take this long to build?

**Comment by pprathameshmore** [comment]
No, not that much. It will take only 2 minutes.

**Comment by Shankhanil** [comment]
Have you reviewed the code?

**Comment by pprathameshmore** [comment]
Yes, check the review for changes.

**Comment by Shankhanil** [comment]
I think this issue could be resolved and closed safely.

**Comment by pprathameshmore** [comment]
The genre route is not working.
