### ISSUE TITLE
Get all genres avaible!

### ISSUE THREAD

**Issue by EufranioDiogo** [pprathameshmore/QuoteGarden#16]
Hello, I'm doing a web app that it do a request to the api and I would like to get a list of all genres that are available at the api because with it, I can  select at the existing genres at the api and be able to reach a select genre!

Thanks, I would like to get a response, and I would like to congrats you, it's a very good work!

**Comment by pprathameshmore** [comment]
Yeah. We keep this issue open so other contributors can add this feature.

**Comment by EufranioDiogo** [comment]
Waiting for! And one more time, it's a really good work!

**Comment by masnormen** [comment]
Hi,

I've made a PR for this feature. May you check that out? Thank you!

**Comment by EufranioDiogo** [comment]
Awesome dude! I hoe that he accept your pull request, thanks dude!
