### ISSUE TITLE
Error while running npm command

### ISSUE THREAD

**Issue by SatyaAchanta** [pprathameshmore/QuoteGarden#18]
I came across this repo and quite impressed by the work you did. First of all Kudos for that. When I tried to install npm package, this is what I am seeing. If I am doing anything wrong, please let me know. I also looked into your [NPM Registry](https://www.npmjs.com/package/quotegarden). However, the npm command mentioned there was `npm i quotegarden`

<img width="844" alt="Screen Shot 2020-09-21 at 11 39 52 PM" src="https://user-images.githubusercontent.com/8125473/93842178-f88a5a80-fc63-11ea-949e-d7d18f397a70.png">

**Comment by SatyaAchanta** [comment]
Update: running `npm i quotegarden` garden worked for me, but I had to change my project name in `package.json' file, Initially the dependency I was trying to install was same the package name I am in. So, I changed my package name inside package.json file to something other than dependency name.

**Comment by pprathameshmore** [comment]
Is it working now? @SatyaAchanta

**Comment by SatyaAchanta** [comment]
@pprathameshmore  Yes, I could get dependency installed. However, I tried to run the project locally and I see exception in connecting to database. So, my assumption in installing dependency is that we are going to connect to db through dependency, correct ?.  If so, you might have to look into why DB connections are not successful.

**Comment by SatyaAchanta** [comment]
If not, is there any test Database that we can connect to run application locally ?

**Comment by pprathameshmore** [comment]
@SatyaAchanta Database link is confidential, so it is not available publicly.
