### ISSUE TITLE
Get quotes by genre

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/QuoteGarden#20]
Get quotes by the filtering based genre.

**Comment by vivek32ta** [comment]
Hi @pprathameshmore 

Aren't quotes already being filtered by genre?? (Reference [here](https://github.com/pprathameshmore/QuoteGarden#get-quotes-by-genre).)

If you could explain what exactly you need.. I'd love to work on this!

**Comment by pprathameshmore** [comment]
@vivek32ta Get quotes by the filtering based genre.
