### ISSUE TITLE
Write test cases

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/QuoteGarden#24]
Write test cases to test the code.

**Comment by daisyjanejohnson** [comment]
Working on this! :)

**Comment by julieg18** [comment]
I'd be happy to help! Is there anything else I need to know about the tests you want written for the API?

**Comment by pprathameshmore** [comment]
Write test cases for the local version of the app. You can use any good JS library for testing.

**Comment by julieg18** [comment]
Do you have a database for the tests or should I create my own?

**Comment by pprathameshmore** [comment]
Create your own! I don't any idea of testing.
