### ISSUE TITLE
I developed a free iOS app using your API

### ISSUE THREAD

**Issue by FranicevicNikola** [pprathameshmore/QuoteGarden#28]
First of all, thank you for the API. Let me know what do you think of the app (https://apps.apple.com/us/app/spontaneous-random-quotes/id1538265374#?platform=iphone)

**Comment by pprathameshmore** [comment]
Hi mate,

Thanks for using our API for this app. 😊

I have been improving the code of QuoteGarden. Recently I improved code, added more flexibility to API. 😍

Please do upgrade to the new version of API i.e. V3. 🥰

E.g. `https://quote-garden.herokuapp.com/api/v3/quotes/random?author=Bill Gates&count=1`

I Will push new updates on 19-December-2020. 😇

Apology for the inconvenience. 😌

Thanks, 😀
