### ISSUE TITLE
@pprathameshmore/quotegardennpm@1.1.0 not working

### ISSUE THREAD

**Issue by dubar-jeremy** [pprathameshmore/QuoteGarden#32]
Hi,

`npm install @pprathameshmore/quotegardennpm@1.1.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pprathameshmore%2fquotegardennpm - Not found
npm ERR! 404 
npm ERR! 404  '@pprathameshmore/quotegardennpm@1.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeremy/.npm/_logs/2021-03-21T11_31_55_639Z-debug.log`

**Comment by pprathameshmore** [comment]
@dubar-jeremy Thanks for reporting. I will fix this issue and let you know as soon as possible.

**Comment by pprathameshmore** [comment]
This library has been deprecated!
