### ISSUE TITLE
The api is not working

### ISSUE THREAD

**Issue by PatrickNv23** [pprathameshmore/QuoteGarden#49]
Currently the api is not working.

![Screenshot_20221130_103957](https://user-images.githubusercontent.com/82006807/204960509-e482a5a2-88f0-4203-a8dd-f644182238db.png)

**Comment by pprathameshmore** [comment]
Heroku stopped 🚫  supporting the free tier

**Comment by PatrickNv23** [comment]
😢

**Comment by mariofdezzz** [comment]
deploy on vercel please, its free :)
2 click change

**Comment by mariofdezzz** [comment]
@pprathameshmore are you planning to fix it? I would be opened to help

**Comment by pprathameshmore** [comment]
@mariofdezzz yes

**Comment by Patil-Tanmay** [comment]
@pprathameshmore if the fixing gonna take time then can you share your quotes database so we can also use it to host.

**Comment by Gameonn** [comment]
@pprathameshmore I can contribute in fixing the issue.

**Comment by pprathameshmore** [comment]
Sure @Gameonn

**Comment by Gameonn** [comment]
@pprathameshmore What options do we have? Should we use a different provider other than `heroku`?

**Comment by Patil-Tanmay** [comment]
@Gameonn We can try render.com but the issue is it has a high response time during cold start so we might need to write some cron jobs to keep the API alive at all times.

**Comment by Gameonn** [comment]
@Patil-Tanmay Does render.com offer free hosting? And would it be a good replacement for `Heroku`.

**Comment by Gameonn** [comment]
@Patil-Tanmay Can you please share how can I help in migrating the existing server code to railway.app?

**Comment by Patil-Tanmay** [comment]
@Gameonn it's a straightforward process but the main issue here is getting the database that this repo uses and host it on your mongo db & then only you can host it on railway or on render.
Link to the dataset to Host on your DB -> [Link](https://www.researchgate.net/publication/304742521_CSV_dataset_of_76000_quotes_suitable_for_quotes_recommender_systems_or_other_analysis)

**Comment by pprathameshmore** [comment]
I will try these platforms to deploy it.

**Comment by pprathameshmore** [comment]
API is started working: https://quote-garden.onrender.com/

**Comment by Patil-Tanmay** [comment]
One Issue with renderer @pprathameshmore is that cold start up time is too much. So to keep it alive it's better to write some cron jobs for it.

**Comment by pprathameshmore** [comment]
Sure
