### ISSUE TITLE
Not working - Page Not found

### ISSUE THREAD

**Issue by AbdullahProgrammer426351** [pprathameshmore/QuoteGarden#53]
It was working fine almost 2 weeks ago. But now, it is not working. I tried to visit the page but there is an error :
 Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command

**Comment by pprathameshmore** [comment]
API is started working: https://quote-garden.onrender.com/
