### ISSUE TITLE
Using QuoteGarden in Production-level Android App

### ISSUE THREAD

**Issue by Vikash-Singh-Bhadoriya** [pprathameshmore/QuoteGarden#55]
Hey @pprathameshmore,

I am thinking to create a Fitness Android App that uses your API to get Quotes, which will be a side feature to give some inspiration to getting fit
I am thinking to upload it to Google Play Stores & Other Stores.

Can I have your permission to upload the app to Store & possibly earn money through it?
The LICENSE tells us that we can use your API for commercial purposes.

Also,
What if my app gained some downloads, will it increase the traffic on the server?
Will the traffic increase the cost? Do I need to pay the cost?
Can you explain in detail?

**Comment by pprathameshmore** [comment]
Currently, I am using a free service. In the future, if it is gaining popularity, you can share some income percentage.
