### ISSUE TITLE
Can't get quotes from an author

### ISSUE THREAD

**Issue by Shankhanil** [pprathameshmore/QuoteGarden#6]
I am using the Quote Garden API to build a new desktop app called MotivateU, and I want to introduce this feature where you can get a random quote from an author. I am using the link 

https://quote-garden.herokuapp.com/api/v2/authors/:%22Carl%20Sandburg%22

to get all quotes from an author (say Card Sandburg), but it is returning no quotes. 
`{"statusCode":200,"totalPages":543,"currentPage":1,"quotes":[]}`

Can you help @pprathameshmore

**Comment by pprathameshmore** [comment]
Hello @Shankhanil 

Actually there no quotes for author Card Sandburg. I checked API `https://quote-garden.herokuapp.com/api/v2/authors/Card%20Sandburg`

**Comment by Shankhanil** [comment]
@pprathameshmore , I actually mentioned **Carl Sandburg**. But yes, I realized I had made an error in the API URL format.

**Comment by pprathameshmore** [comment]
Yeah! @Shankhanil 
When you done with your app, inform me of making an issue. So I can mention your app in the README file.

**Comment by Shankhanil** [comment]
Certainly!
