### ISSUE TITLE
I want to introduce a feature in my software to donate quotes to QuoteGarden. How do I go about doing that?

### ISSUE THREAD

**Issue by Shankhanil** [pprathameshmore/QuoteGarden#7]

**Comment by Shankhanil** [comment]
@pprathameshmore  pls have a look at the issue

**Comment by pprathameshmore** [comment]
Are you talking about adding new quotes?

**Comment by Shankhanil** [comment]
Yes, I am introducing a feature, where an user can add new quotes to QuoteGarden

**Comment by pprathameshmore** [comment]
But we have to keep secure.

**Comment by Shankhanil** [comment]
Absolutely, what I can do is, I can post the quote data to a temporary API, where the maintainer (you) can review it and approve/reject it.

**Comment by pprathameshmore** [comment]
No, I trust you. You can post directly.

**Comment by Shankhanil** [comment]
Yes, but I can't always trust my users. It may so happen, that the user is trying to spam, or post meaningless data. I need more ideas on how to prevent it.

**Comment by pprathameshmore** [comment]
I can implement API protection using JWT, so users need to log in to create new quotes.

**Comment by Shankhanil** [comment]
That's a good idea. Can I work on this patch, if you're not yet working on it? 
I can create an issue, and a PR. If you assign this to me, could you also send me relevant sources for a quick readup on JWT authentication? @pprathameshmore

**Comment by pprathameshmore** [comment]
Do you know Node.js?

**Comment by Shankhanil** [comment]
Yes, as a beginner.

**Comment by pprathameshmore** [comment]
Okay! You can! But currently facing issue https://github.com/pprathameshmore/QuoteGarden/issues/9

**Comment by Shankhanil** [comment]
I will look into issue #9 .

**Comment by PrithiPal** [comment]
In regards to the validity of user-added quotes, some open-source APIs usually have a feedback system that contains two buttons: like or dislike, which is usually a POST request. Another variant is just voted with each quote act as a weight to how likely this is to be randomly generated. This approach will likely be little algorithmic heavy.

**Comment by Shankhanil** [comment]
We can try out the feedback-system approach.

**Comment by pprathameshmore** [comment]
Yes
