### ISSUE TITLE
Fix request timeout

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/QuoteGarden#9]

**Comment by PrithiPal** [comment]
If this issue is about not loading the API endpoint, I would like to add to it. On the heroku server end, the API owner can look through ``` heroku logs --tail```.

**Comment by Shankhanil** [comment]
I'll take a look.

**Comment by pprathameshmore** [comment]
I added lots of new quotes to the database.  Currently, we have 76000 quotes. When fetching a random quote from that huge quote collection. It takes more than 30 seconds and Heroku doesn't allow to hang request for more than 30 seconds. So we have to work Job queueing. https://devcenter.heroku.com/articles/request-timeout

**Comment by Atoo35** [comment]
So is the issue fixed or not? I am confused

**Comment by Shankhanil** [comment]
@Atoo35 I am taking a look on this issue.

**Comment by pprathameshmore** [comment]
@Shankhanil Hello, I can add you as a collaborator on Heroku. Could you give your email? So you can easily fix this issue.

**Comment by Shankhanil** [comment]
Absolutely. Here is my email shankha.rik@gmail.com

Shankhanil Ghosh

**Comment by Shankhanil** [comment]
I've gone through the codebase , and here are some clarifications I need.

1. I will implement job queuing on the _get random quotes_ function. Which means, that when the app receives a `GET /quotes` request from the client, it will push the `quoteController.random` job to the Queue.
2. The worker.js would then work on it accordingly. Meaning the `start()` function in a worker dyno would basically contain the program logic for `quoteController.random`

This is what I have understood from the documentation and code base. Am I right, or am I going wrong? @pprathameshmore

**Comment by pprathameshmore** [comment]
Yes, actually even don't much about workers. I am busy with another project that why I am not able to focus on this issue.

**Comment by Shankhanil** [comment]
No problem. I am starting to code the solution based on my understanding, and let's see where that lands me

**Comment by pprathameshmore** [comment]
Yeah. Thank you so much.

I also free now.

**Comment by pprathameshmore** [comment]
Any updates?

**Comment by Shankhanil** [comment]
It would be nice if you could read-up on how workers work. And then you can guide me a bit?

**Comment by PrithiPal** [comment]
I was wondering how the worker system is going to solve the huge-database access problem?

**Comment by Shankhanil** [comment]
I think what needs to be done, is to split the database, and then run worker to solve time out problem

**Comment by pprathameshmore** [comment]
I guess NoSQL comes with an inbuild clustering feature.

**Comment by Shankhanil** [comment]
I really need help on this one,

**Comment by PrithiPal** [comment]
So if the fetching the random quote is the problem at hand now, Can't you just generate a random number 0 and max number of quotes followed by accessing the quote by this primary key?. Fetching single record by primary-key shouldn't be that bad.

**Comment by Shankhanil** [comment]
I think we need to see how the database is structured.

**Comment by pprathameshmore** [comment]
The main problem is that caused by counting the whole collection's count for every request. That can could cause slowing the performance.

**Comment by PrithiPal** [comment]
IMHO, the structure can be as it is. You can just create another table within the database to store metadata about the quotes table. One of the entries in this new table will be current number of quotes. This can be updated as soon as new quote is inserted. However, you already have database full of quotes, I think the metatable and then inserting the current count is needed to be inserted manually. Then, when requesting a random quote, the code can look up max number/ total number of quotes from this metatable. The fetching will be a constant time in the case every time.

**Comment by pprathameshmore** [comment]
Well! API is up and running!
